import { EndpointDefinition } from './app.models';

export const API_BASE_URL = 'https://iotsecurity-production.up.railway.app/api';

export const ENDPOINTS: EndpointDefinition[] = [
  {
    key: 'homes',
    label: 'Hogares',
    group: 'core',
    path: 'core/homes/',
    icon: 'pi pi-home',
    accent: 'teal',
    description: 'Unidades residenciales registradas',
    allowedRoles: ['admin', 'operador', 'lector'],
  },
  {
    key: 'zones',
    label: 'Zonas',
    group: 'core',
    path: 'core/zones/',
    icon: 'pi pi-map-marker',
    accent: 'cyan',
    description: 'Sectores monitoreados por sensores',
    allowedRoles: ['admin', 'operador', 'lector'],
  },
  {
    key: 'sensor-readings',
    label: 'Lecturas',
    group: 'core',
    path: 'core/sensor-readings/',
    icon: 'pi pi-chart-line',
    accent: 'emerald',
    description: 'Telemetria recibida desde dispositivos',
    allowedRoles: ['admin', 'operador', 'lector'],
  },
  {
    key: 'motion-events',
    label: 'Movimiento',
    group: 'core',
    path: 'core/motion-events/',
    icon: 'pi pi-bolt',
    accent: 'amber',
    description: 'Eventos de deteccion recientes',
    allowedRoles: ['admin', 'operador', 'lector'],
  },
  {
    key: 'system-alerts',
    label: 'Alertas',
    group: 'core',
    path: 'core/system-alerts/',
    icon: 'pi pi-exclamation-triangle',
    accent: 'rose',
    description: 'Incidentes y estados criticos',
    allowedRoles: ['admin', 'operador', 'lector'],
  },
  {
    key: 'nodes',
    label: 'Nodos IoT',
    group: 'devices',
    path: 'devices/nodes/',
    icon: 'pi pi-sitemap',
    accent: 'indigo',
    description: 'Controladores conectados al sistema',
    allowedRoles: ['admin', 'operador', 'lector'],
  },
  {
    key: 'sensors',
    label: 'Sensores',
    group: 'devices',
    path: 'devices/sensors/',
    icon: 'pi pi-compass',
    accent: 'sky',
    description: 'Dispositivos de captura y monitoreo',
    allowedRoles: ['admin', 'operador', 'lector'],
  },
  {
    key: 'actuators',
    label: 'Actuadores',
    group: 'devices',
    path: 'devices/actuators/',
    icon: 'pi pi-sliders-h',
    accent: 'orange',
    description: 'Elementos que ejecutan comandos fisicos',
    allowedRoles: ['admin', 'operador', 'lector'],
  },
  {
    key: 'automation-settings',
    label: 'Automatizaciones',
    group: 'automation',
    path: 'automation/automation-settings/',
    icon: 'pi pi-cog',
    accent: 'violet',
    description: 'Reglas y umbrales configurados',
    allowedRoles: ['admin', 'operador'],
  },
  {
    key: 'lighting-statuses',
    label: 'Iluminacion',
    group: 'automation',
    path: 'automation/lighting-statuses/',
    icon: 'pi pi-lightbulb',
    accent: 'yellow',
    description: 'Estados de luces y escenas',
    allowedRoles: ['admin', 'operador', 'lector'],
  },
  {
    key: 'alarm-statuses',
    label: 'Alarmas',
    group: 'automation',
    path: 'automation/alarm-statuses/',
    icon: 'pi pi-shield',
    accent: 'red',
    description: 'Activacion y salud de alarmas',
    allowedRoles: ['admin', 'operador', 'lector'],
  },
  {
    key: 'remote-commands',
    label: 'Comandos',
    group: 'automation',
    path: 'automation/remote-commands/',
    icon: 'pi pi-send',
    accent: 'blue',
    description: 'Ordenes remotas solicitadas',
    allowedRoles: ['admin', 'operador'],
  },
  {
    key: 'command-responses',
    label: 'Respuestas',
    group: 'automation',
    path: 'automation/command-responses/',
    icon: 'pi pi-reply',
    accent: 'lime',
    description: 'Resultados reportados por nodos',
    allowedRoles: ['admin', 'operador'],
  },
  {
    key: 'users',
    label: 'Usuarios',
    group: 'users',
    path: 'users/users/',
    icon: 'pi pi-users',
    accent: 'fuchsia',
    description: 'Cuentas con acceso al backend',
    allowedRoles: ['admin'],
  },
  {
    key: 'roles',
    label: 'Roles',
    group: 'users',
    path: 'users/roles/',
    icon: 'pi pi-id-card',
    accent: 'purple',
    description: 'Perfiles y niveles de acceso',
    allowedRoles: ['admin'],
  },
  {
    key: 'user-roles',
    label: 'Asignaciones',
    group: 'users',
    path: 'users/user-roles/',
    icon: 'pi pi-key',
    accent: 'stone',
    description: 'Relacion usuario-rol',
    allowedRoles: ['admin'],
  },
  {
    key: 'notifications',
    label: 'Notificaciones',
    group: 'users',
    path: 'users/notifications/',
    icon: 'pi pi-bell',
    accent: 'pink',
    description: 'Mensajes enviados a usuarios',
    allowedRoles: ['admin', 'operador'],
  },
  {
    key: 'system-audits',
    label: 'Auditoria',
    group: 'users',
    path: 'users/system-audits/',
    icon: 'pi pi-history',
    accent: 'zinc',
    description: 'Trazabilidad de acciones',
    allowedRoles: ['admin'],
  },
];
